<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.14">
  <POU Name="FB_ErrorLogger" Id="{f83db9ac-a4cd-4080-900e-a00207e1af95}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC FB_ErrorLogger
VAR_INPUT
	
END_VAR
VAR_OUTPUT
	
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ErrorLogger">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>